# Generated by Django 2.0.7 on 2018-07-22 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=1024)),
                ('ids', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorylistMovie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('watch_id', models.IntegerField()),
                ('watched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(default='watch', max_length=64)),
                ('type', models.CharField(default='movie', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HistorylistShow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('watch_id', models.IntegerField()),
                ('watched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(default='watch', max_length=64)),
                ('type', models.CharField(default='show', max_length=64)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Episode', verbose_name='Episode watched')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('year', models.IntegerField()),
                ('trakt_id', models.IntegerField(default=-1)),
                ('slug', models.CharField(max_length=1024)),
                ('imdb_id', models.CharField(max_length=256)),
                ('tmdb_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('year', models.IntegerField()),
                ('ids', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraktSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_slug', models.CharField(max_length=1024)),
                ('token', models.CharField(max_length=128)),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('update_dt', models.DateTimeField(auto_now_add=True, verbose_name='Last updated')),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistMovie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('type', models.CharField(default='movie', max_length=64)),
                ('listed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_slug', models.CharField(max_length=1024)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Movie', verbose_name='Movie watched')),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistShow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('type', models.CharField(default='show', max_length=64)),
                ('listed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Show', verbose_name='Show watched')),
            ],
        ),
        migrations.AddField(
            model_name='historylistshow',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Show', verbose_name='Show watched'),
        ),
        migrations.AddField(
            model_name='historylistmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Movie', verbose_name='Movie watched'),
        ),
    ]
