# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 02:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('35b71893-bf35-4750-916b-2eb24d6420af'), primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('year', models.IntegerField()),
                ('ids', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistShow',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a08436b3-f297-4073-adc0-889210da9f56'), primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('type', models.CharField(default=b'movie', max_length=64)),
                ('listed_at', models.DateTimeField(default=datetime.datetime(2018, 7, 22, 2, 42, 3, 815211))),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('381b96fc-aaa5-4b25-94fc-3ead5ffd9dbc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64d9cfa8-4564-435a-a523-edf25e8eb765'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='listed_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 2, 42, 3, 814500)),
        ),
        migrations.AddField(
            model_name='watchlistshow',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Movie', verbose_name=b'Show watched'),
        ),
    ]
