# Generated by Django 2.0.7 on 2018-07-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='ids',
        ),
        migrations.RemoveField(
            model_name='show',
            name='ids',
        ),
        migrations.AddField(
            model_name='episode',
            name='imdb_id',
            field=models.CharField(default='-1', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.CharField(default='test', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='trakt_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='episode',
            name='tvdb_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='episode',
            name='tvrage_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='historylistmovie',
            name='user_slug',
            field=models.CharField(default='jrgoodle', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historylistshow',
            name='user_slug',
            field=models.CharField(default='jrgoodle', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='imdb_id',
            field=models.CharField(default='-1', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.CharField(default='test', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='trakt_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='show',
            name='tvdb_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='show',
            name='tvrage_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='watchlistshow',
            name='user_slug',
            field=models.CharField(default='jrgoodle', max_length=1024),
            preserve_default=False,
        ),
    ]
