# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 03:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20180722_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorylistMovie',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7f72bdf5-9dab-4380-9fe5-0a1c556f8093'), primary_key=True, serialize=False)),
                ('watched_at', models.DateTimeField(default=datetime.datetime(2018, 7, 22, 3, 13, 40, 199202))),
                ('action', models.CharField(default=b'movie', max_length=64)),
                ('type', models.CharField(default=b'movie', max_length=64)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a2035066-d80a-4b0f-b46a-eb0fb4353af8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4b986be-41e8-4037-a0c0-f58cb31c587c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97537b14-c971-41a3-b291-ea4a225c3cb9'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='listed_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 3, 13, 40, 197920)),
        ),
        migrations.AlterField(
            model_name='watchlistshow',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20a7a65a-8e81-48fa-927f-b183572c0db0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlistshow',
            name='listed_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 3, 13, 40, 198558)),
        ),
        migrations.AddField(
            model_name='historylistmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Movie', verbose_name=b'Movie watched'),
        ),
    ]
