# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 03:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20180722_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1f5c4ba7-d871-4331-ad86-b1fda965a753'), primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=1024)),
                ('ids', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorylistShow',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('56fbb03c-bc28-4199-959f-f1497f25b2f0'), primary_key=True, serialize=False)),
                ('watch_id', models.IntegerField()),
                ('watched_at', models.DateTimeField(default=datetime.datetime(2018, 7, 22, 3, 59, 34, 326630))),
                ('action', models.CharField(default=b'watch', max_length=64)),
                ('type', models.CharField(default=b'show', max_length=64)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Episode', verbose_name=b'Episode watched')),
            ],
        ),
        migrations.RenameField(
            model_name='historylistmovie',
            old_name='rank',
            new_name='watch_id',
        ),
        migrations.AlterField(
            model_name='historylistmovie',
            name='action',
            field=models.CharField(default=b'watch', max_length=64),
        ),
        migrations.AlterField(
            model_name='historylistmovie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f072ed18-110c-42aa-a442-82352fce9914'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historylistmovie',
            name='watched_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 3, 59, 34, 325950)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36e8a107-33eb-4a87-a987-14cdc976c7f9'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66366115-5128-4e92-8ad1-75548f925207'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6d7b9ef8-15cb-4dc5-bf77-5fea5ce23793'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='listed_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 3, 59, 34, 324571)),
        ),
        migrations.AlterField(
            model_name='watchlistshow',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4894cac8-081f-4153-81f6-4400ebd7e975'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlistshow',
            name='listed_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 3, 59, 34, 325238)),
        ),
        migrations.AlterField(
            model_name='watchlistshow',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Show', verbose_name=b'Show watched'),
        ),
        migrations.AlterField(
            model_name='watchlistshow',
            name='type',
            field=models.CharField(default=b'show', max_length=64),
        ),
        migrations.AddField(
            model_name='historylistshow',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Show', verbose_name=b'Show watched'),
        ),
    ]
