# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20180722_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='tvrage_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
