# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20180722_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b18b7302-882a-4c1f-9f7b-7cc37af3fe27'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historylistmovie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0530a749-eb1f-4f48-96f4-c26fd3bc43a2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historylistmovie',
            name='watched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historylistshow',
            name='id',
            field=models.UUIDField(default=uuid.UUID('645b1949-0d30-4010-ba72-9760bde6c1e5'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historylistshow',
            name='watched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c9694072-2e95-4aa8-807e-e522478a7f9d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.UUIDField(default=uuid.UUID('767cbe97-20e5-4869-95ff-80bee939880e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a6824184-11bf-4716-a02f-f69994d9d03a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='listed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='watchlistshow',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cf9620d9-3d4c-4e6e-aaf2-866d26892865'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlistshow',
            name='listed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
