# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_auto_20180722_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistmovie',
            name='user_slug',
            field=models.CharField(default='jrgoodle', max_length=1024),
            preserve_default=False,
        ),
    ]
