# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_watchlistmovie_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='traktsession',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traktsession',
            name='update_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'Last updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traktsession',
            name=b'id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
